# Generated by Django 5.2.5 on 2025-09-30 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('type', models.CharField(choices=[('postgres', 'PostgreSQL'), ('http', 'HTTP API'), ('mock', 'Mock')], max_length=20)),
                ('host', models.CharField(blank=True, max_length=200)),
                ('port', models.IntegerField(default=5432)),
                ('database', models.CharField(blank=True, max_length=120)),
                ('username', models.CharField(blank=True, max_length=120)),
                ('password', models.CharField(blank=True, max_length=120)),
                ('base_url', models.URLField(blank=True)),
                ('auth_token', models.CharField(blank=True, max_length=255)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.organization')),
            ],
            options={
                'unique_together': {('organization', 'name')},
            },
        ),
    ]
